In [10]:
!pip install pymysql
!pip install sqlalchemy

Requirement already satisfied: pymysql in c:\users\sanch\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: sqlalchemy in c:\users\sanch\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sanch\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)

In [11]:
import pandas as pd
import numpy as np

import pymysql                        # for getting data from a SQL database
from sqlalchemy import create_engine  # for establishing the connection and authentication

from getpass import getpass  # To get the password without showing the input

In [12]:
password = getpass()

········

In [13]:
connection_string = 'mysql+pymysql://root:'+password+'@localhost/sakila'
engine = create_engine(connection_string)

In [14]:
type(engine)

sqlalchemy.engine.base.Engine

In [9]:
data = pd.read_sql_query('SELECT * FROM sakila.rental', engine)
data.head()

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Create a query or queries to extract the information you think may be relevant for building the prediction model. It should include some film features and some rental features (X).

In [7]:
data2 = pd.read_sql_query('SELECT * FROM sakila.film', engine)
data2.head()

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [7]:
data = pd.read_sql_query('SELECT * FROM sakila.rental',engine)

In [8]:
def rentals_month(engine,month,year): 
    query= "SELECT * FROM rental WHERE Month(rental_date) = "+str(month)+ " and Year(rental_date) = "+str(year)
    data = pd.read_sql_query(query, engine) 
    return data

In [9]:
may=rentals_month(engine,5,2005)

In [10]:
may

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
1151,1153,2005-05-31 21:36:44,2725,506,2005-06-10 01:26:44,2,2006-02-15 21:30:53
1152,1154,2005-05-31 21:42:09,2732,59,2005-06-08 16:40:09,1,2006-02-15 21:30:53
1153,1155,2005-05-31 22:17:11,2048,251,2005-06-04 20:27:11,2,2006-02-15 21:30:53
1154,1156,2005-05-31 22:37:34,460,106,2005-06-01 23:02:34,2,2006-02-15 21:30:53
1155,1157,2005-05-31 22:47:45,1449,61,2005-06-02 18:01:45,1,2006-02-15 21:30:53

In [11]:
June = rentals_month(engine,6,2005)

In [12]:
June

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1158,2005-06-14 22:53:33,1632,416,2005-06-18 21:37:33,2,2006-02-15 21:30:53
1,1159,2005-06-14 22:55:13,4395,516,2005-06-17 02:11:13,1,2006-02-15 21:30:53
2,1160,2005-06-14 23:00:34,2795,239,2005-06-18 01:58:34,2,2006-02-15 21:30:53
3,1161,2005-06-14 23:07:08,1690,285,2005-06-21 17:12:08,1,2006-02-15 21:30:53
4,1162,2005-06-14 23:09:38,987,310,2005-06-23 22:00:38,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
2306,3465,2005-06-21 22:10:01,1488,510,2005-06-30 21:35:01,1,2006-02-15 21:30:53
2307,3466,2005-06-21 22:13:33,371,226,2005-06-25 21:01:33,2,2006-02-15 21:30:53
2308,3467,2005-06-21 22:19:25,729,543,2005-06-27 00:03:25,2,2006-02-15 21:30:53
2309,3468,2005-06-21 22:43:45,2899,100,2005-06-30 01:49:45,1,2006-02-15 21:30:53
2310,3469,2005-06-21 22:48:59,4087,181,2005-06-28 19:32:59,1,2006-02-15 21:30:53

3. Develop a Python function called rental_count_month that takes the DataFrame provided by rentals_month as input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year.

The function should also include the month and year as parameters and use them to name the new column according to the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".

Hint: Consider making use of pandas groupby()

In [13]:
data1 = pd.DataFrame(may)

In [14]:
import pandas as pd

def rental_count_month(may, month, year):
    data1 = may.loc[(may['rental_date'].dt.year == year) & (may['rental_date'].dt.month == month)]\
            .groupby('customer_id')['rental_id'].count().reset_index()
    data1 = data1.rename(columns={'rental_id': f'rentals_{month}_{year}'})
    return data1


month = 5
year = 2005

In [15]:
may_1 = rental_count_month(data1, month, year)

In [16]:
may_1

     customer_id  rentals_5_2005
0              1               2
1              2               1
2              3               2
3              5               3
4              6               3
..           ...             ...
515          594               4
516          595               1
517          596               6
518          597               2
519          599               1

[520 rows x 2 columns]

In [22]:
data2 = pd.DataFrame(June)

In [23]:
import pandas as pd

def rental_count_month(June, month, year):
    data2 = June.loc[(June['rental_date'].dt.year == year) & (June['rental_date'].dt.month == month)]\
            .groupby('customer_id')['rental_id'].count().reset_index()
    data2 = data2.rename(columns={'rental_id': f'rentals_{month}_{year}'})
    return data2


month = 6
year = 2005

In [24]:
june_1 = rental_count_month(data2, month, year)

In [25]:
june_1

     customer_id  rentals_6_2005
0              1               7
1              2               1
2              3               4
3              4               6
4              5               5
..           ...             ...
585          595               2
586          596               2
587          597               3
588          598               1
589          599               4

[590 rows x 2 columns]

4. Create a Python function called compare_rentals that takes two DataFrames as input containing the number of rentals made by each customer in different months and years. The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.

In [26]:
def compare_rentals(may_1, june_1):
    
    merged_df = pd.merge(may_1, june_1, on='customer_id')
    
    merged_df['difference'] = merged_df[may_1.columns[1]] - merged_df[june_1.columns[1]]

    return merged_df

In [27]:
df = compare_rentals(may_1, june_1)

In [29]:
customer_rentals_may_1 = rental_count_month(data1, 5, 2005)

customer_rentals_june_1 = rental_count_month(data2, 6,2005)


comparative = compare_rentals(customer_rentals_may_1, customer_rentals_june_1)
comparative

     customer_id  rentals_5_2005  rentals_6_2005  difference
0              1               2               7          -5
1              2               1               1           0
2              3               2               4          -2
3              5               3               5          -2
4              6               3               4          -1
..           ...             ...             ...         ...
507          594               4               6          -2
508          595               1               2          -1
509          596               6               2           4
510          597               2               3          -1
511          599               1               4          -3

[512 rows x 4 columns]

In [ ]:
If we compare june and may, the conclusion is that in June the rentals by customers have increased.
We haven't analyzed the nexts month but I also recommend to proceed with it because on August,if we consider that it is a family holiday month, there are a high level of probability that the rentals have been increased as well.